#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2022 Arcangelo Massari <arcangelo.massari@unibo.it>
#
# Permission to use, copy, modify, and/or distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright notice
# and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED 'AS IS' AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
# ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.

name: Run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  CheckCoverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip3 install poetry
        sudo apt install -y python-is-python3
        poetry install
    - name: Check the coverage
      run: |
        poetry run coverage run --rcfile=test/coverage/.coveragerc
    - name: Generate the badge
      run: |
        mv .coverage test/coverage/
        cd test/coverage/
        rm -f coverage.svg
        poetry run coverage-badge -o coverage.svg
    - uses: actions/upload-artifact@v4
      with:
          name: coverage-artifact
          path: test/coverage/
  PublishBadge:
    runs-on: ubuntu-latest
    needs: CheckCoverage
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: coverage-artifact
        path: test/coverage/
    - name: Publish the badge on the GitHub repo
      run: |
        git pull
        git add test/coverage/.coverage
        git add test/coverage/coverage.svg
        git config --global user.name 'arcangelo7'
        git config --global user.email 'arcangelomas@gmail.com'
        git commit -m 'Coverage updated' || echo "No changes to commit"
        git push
